### ISSUE TITLE
Delete this line

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/base-redcode#16]
It's not make sense and can be deleted [`setTextColor(ContextCompat.getColor(context, android.R.color.black))`](https://github.com/pedrofsn/base-redcode/blob/04b6ca1583d94cd3c45d0b8095b367404f26c578/base/src/main/java/br/com/redcode/base/extensions/ExtensionTextView.kt#L46)

**Comment by salvatorelaiso** [comment]
Can I take it?

**Comment by pedrofsn** [comment]
I'm sorry @salvatorelaiso and @swarn4399, but @suvidsahay taked it first.
