### ISSUE TITLE
Put libraries in one gradle file

### ISSUE THREAD

**Issue by pedrofsn** [pedrofsn/base-redcode#6]
To setup dependencies like [this](https://github.com/karntrehan/Posts/blob/master/build.gradle) and use like [this](https://github.com/karntrehan/Posts/blob/master/core/build.gradle)

**Comment by DeKaN** [comment]
Can I use `buildSrc` feature for solving this issue?

**Comment by pedrofsn** [comment]
Hi @DeKaN, I don't know how could be this approach. 
Can you show me how it is before you start? Maybe other repo as sample.

I'm asking this because I don't want waste your precious collaboration time, if this approach cannot be fill the issue requirements.

**Comment by DeKaN** [comment]
Dependencies will be described in a separate file like https://gist.github.com/DeKaN/02df738e649fc705ed9b99ff3bc036c7

And you can use them in the Gradle script as written at your second link.

By the way, Gradle scripts may be written in Kotlin or Groovy. Which one do you prefer?

**Comment by pedrofsn** [comment]
Wow @DeKaN it's very nice. I did something like that in Groovy in other repository. I think you can proceed with this issue and please, migrate gradle scripts to kotlin as you suggested. 

I never used gradle scripts in Kotlin and I think it's a good improvement and moment to learn! :D
